# -*- coding: utf-8 -*-
"""visual engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXiH3DGybWMo6UHqUVqOVZYeCerah9PV

## visual engine
"""

!pip install streamlit
import streamlit as st
from diffusers import StableDiffusionPipeline
import torch

st.title("Image Generation with Stable Diffusion")

@st.cache_resource
def load_model():
    model_id = "dreamlike-art/dreamlike-diffusion-1.0"
    pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16, use_safetensors=True)
    pipe = pipe.to("cuda")
    return pipe

pipe = load_model()

prompt = st.text_input("Enter your prompt for image generation:", "a bike running in the highway")

if st.button("Generate Image"):
    if prompt:
        with st.spinner("Generating your image..."):
            image = pipe(prompt).images[0]
            st.image(image, caption=prompt, use_column_width=True)
    else:
        st.warning("Please enter a prompt to generate an image.")

#diffusers is a hugging face page for using diffusion models from huggingface hub
!pip install diffusers transformers accelerate

from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt
import torch

!pip show torch

model_id1 = "dreamlike-art/dreamlike-diffusion-1.0"
model_id2 = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = StableDiffusionPipeline.from_pretrained(model_id1, torch_dtype=torch.float16, use_safetensors=True)
pipe = pipe.to("cuda")

def generate_image(pipe, prompt, params):
  img = pipe(prompt, **params).images

  num_images = len(img)
  if num_images>1:
    fig, ax = plt.subplots(nrows=1, ncols=num_images)
    for i in range(num_images):
      ax[i].imshow(img[i]);
      ax[i].axis('off');

  else:
    fig = plt.figure()
    plt.imshow(img[0]);
    plt.axis('off');
  plt.tight_layout()

image = pipe(prompt).images[0]

prompt = input("Enter your prompt for image generation: ")

params = {}

generate_image(pipe, prompt, params)